import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Navbar from '../components/Navbar'
import Results from '../components/Results'
import requests from '../utils/requests'

export default function Home({results}) {
  
  return (
    <>
      <Head>
        <title>Hulu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* heder */}
      <Header></Header>
      {/* Nav */}
      <Navbar></Navbar>
      {/* Results */}
      <Results results={results} ></Results>

    </>
  )
}

export async function getServerSideProps(context) {
  const genre = context.query.genre;
  const request = await fetch(  `https://api.themoviedb.org/3${ requests[genre]?.url || requests.fetchTrending.url }`  
  ).then((res)=>res.json());
  
  return {
    props: {
      results: request.results,
    },
  };

}